version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_DATABASE: ${KEYCLOAK_DB}
      KC_HOSTNAME: localhost
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on:
      - postgres
    command: start-dev
    volumes:
      - type: volume
        source: keycloak-volume
        target: /opt/keycloak/data/
    networks:
      - keycloak-network

  fastapi:
    build: ./keycloak_fastapi
    ports:
      - "${FASTAPI_PORT}:5000"
    environment:
      DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${FASTAPI_DB}
    depends_on:
      - keycloak
      - postgres
    volumes:
      - ./keycloak_fastapi:/app
    networks:
      - keycloak-network

volumes:
  postgres_data:
  keycloak-volume:

networks:
  keycloak-network:
    driver: bridge
