"""init

Revision ID: c92c0baa48e7
Revises: 
Create Date: 2024-07-16 06:33:14.843716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c92c0baa48e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_provider_config')
    op.drop_index('idx_auth_flow_realm', table_name='authentication_flow')
    op.drop_table('authentication_flow')
    op.drop_index('idx_defcls_realm', table_name='default_client_scope')
    op.drop_index('idx_defcls_scope', table_name='default_client_scope')
    op.drop_table('default_client_scope')
    op.drop_index('idx_fu_credential', table_name='fed_user_credential')
    op.drop_index('idx_fu_credential_ru', table_name='fed_user_credential')
    op.drop_table('fed_user_credential')
    op.drop_table('resource_server')
    op.drop_table('databasechangeloglock')
    op.drop_index('idx_role_attribute', table_name='role_attribute')
    op.drop_table('role_attribute')
    op.drop_index('idx_clscope_protmap', table_name='protocol_mapper')
    op.drop_index('idx_protocol_mapper_client', table_name='protocol_mapper')
    op.drop_table('protocol_mapper')
    op.drop_table('realm_smtp_config')
    op.drop_index('idx_auth_config_realm', table_name='authenticator_config')
    op.drop_table('authenticator_config')
    op.drop_index('idx_usr_fed_prv_realm', table_name='user_federation_provider')
    op.drop_table('user_federation_provider')
    op.drop_index('idx_fu_cnsnt_ext', table_name='fed_user_consent')
    op.drop_index('idx_fu_consent', table_name='fed_user_consent')
    op.drop_index('idx_fu_consent_ru', table_name='fed_user_consent')
    op.drop_table('fed_user_consent')
    op.drop_index('idx_fu_group_membership', table_name='fed_user_group_membership')
    op.drop_index('idx_fu_group_membership_ru', table_name='fed_user_group_membership')
    op.drop_table('fed_user_group_membership')
    op.drop_table('realm_localizations')
    op.drop_index('idx_client_id', table_name='client')
    op.drop_table('client')
    op.drop_table('authenticator_config_entry')
    op.drop_index('idx_component_provider_type', table_name='component')
    op.drop_index('idx_component_realm', table_name='component')
    op.drop_table('component')
    op.drop_index('idx_composite', table_name='composite_role')
    op.drop_index('idx_composite_child', table_name='composite_role')
    op.drop_table('composite_role')
    op.drop_table('idp_mapper_config')
    op.drop_index('idx_keycloak_role_client', table_name='keycloak_role')
    op.drop_index('idx_keycloak_role_realm', table_name='keycloak_role')
    op.drop_table('keycloak_role')
    op.drop_index('idx_id_prov_mapp_realm', table_name='identity_provider_mapper')
    op.drop_table('identity_provider_mapper')
    op.drop_index('idx_realm_attr_realm', table_name='realm_attribute')
    op.drop_table('realm_attribute')
    op.drop_index('idx_cl_clscope', table_name='client_scope_client')
    op.drop_index('idx_clscope_cl', table_name='client_scope_client')
    op.drop_table('client_scope_client')
    op.drop_index('idx_usr_fed_map_fed_prv', table_name='user_federation_mapper')
    op.drop_index('idx_usr_fed_map_realm', table_name='user_federation_mapper')
    op.drop_table('user_federation_mapper')
    op.drop_index('idx_us_sess_id_on_cl_sess', table_name='offline_client_session')
    op.drop_table('offline_client_session')
    op.drop_table('client_session_prot_mapper')
    op.drop_table('client_auth_flow_bindings')
    op.drop_table('federated_user')
    op.drop_index('idx_res_scope_scope', table_name='resource_scope')
    op.drop_table('resource_scope')
    op.drop_index('idx_res_serv_pol_res_serv', table_name='resource_server_policy')
    op.drop_table('resource_server_policy')
    op.drop_table('client_user_session_note')
    op.drop_index('idx_offline_uss_by_broker_session_id', table_name='offline_user_session')
    op.drop_index('idx_offline_uss_by_last_session_refresh', table_name='offline_user_session')
    op.drop_index('idx_offline_uss_by_user', table_name='offline_user_session')
    op.drop_table('offline_user_session')
    op.drop_index('idx_realm_clscope', table_name='client_scope')
    op.drop_table('client_scope')
    op.drop_index('idx_fedidentity_feduser', table_name='federated_identity')
    op.drop_index('idx_fedidentity_user', table_name='federated_identity')
    op.drop_table('federated_identity')
    op.drop_table('user_session_note')
    op.drop_index('idx_user_group_mapping', table_name='user_group_membership')
    op.drop_table('user_group_membership')
    op.drop_table('client_session_note')
    op.drop_index('idx_scope_mapping_role', table_name='scope_mapping')
    op.drop_table('scope_mapping')
    op.drop_index('idx_user_attribute', table_name='user_attribute')
    op.drop_index('idx_user_attribute_name', table_name='user_attribute')
    op.drop_index('user_attr_long_values', table_name='user_attribute')
    op.drop_index('user_attr_long_values_lower_case', table_name='user_attribute')
    op.drop_table('user_attribute')
    op.drop_index('idx_update_time', table_name='migration_model')
    op.drop_table('migration_model')
    op.drop_index('idx_group_role_mapp_group', table_name='group_role_mapping')
    op.drop_table('group_role_mapping')
    op.drop_index('idx_clscope_role', table_name='client_scope_role_mapping')
    op.drop_index('idx_role_clscope', table_name='client_scope_role_mapping')
    op.drop_table('client_scope_role_mapping')
    op.drop_table('user_federation_mapper_config')
    op.drop_index('idx_client_session_session', table_name='client_session')
    op.drop_table('client_session')
    op.drop_table('username_login_failure')
    op.drop_index('idx_realm_supp_local_realm', table_name='realm_supported_locales')
    op.drop_table('realm_supported_locales')
    op.drop_table('user_federation_config')
    op.drop_index('idx_realm_master_adm_cli', table_name='realm')
    op.drop_table('realm')
    op.drop_index('idx_user_reqactions', table_name='user_required_action')
    op.drop_table('user_required_action')
    op.drop_table('keycloak_group')
    op.drop_index('idx_usconsent_clscope', table_name='user_consent_client_scope')
    op.drop_table('user_consent_client_scope')
    op.drop_index('idx_ident_prov_realm', table_name='identity_provider')
    op.drop_table('identity_provider')
    op.drop_index('idx_client_init_acc_realm', table_name='client_initial_access')
    op.drop_table('client_initial_access')
    op.drop_index('idx_scope_policy_policy', table_name='scope_policy')
    op.drop_table('scope_policy')
    op.drop_index('idx_req_act_prov_realm', table_name='required_action_provider')
    op.drop_table('required_action_provider')
    op.drop_table('fed_user_consent_cl_scope')
    op.drop_index('idx_group_att_by_name_value', table_name='group_attribute')
    op.drop_index('idx_group_attr_group', table_name='group_attribute')
    op.drop_table('group_attribute')
    op.drop_index('idx_user_email', table_name='user_entity')
    op.drop_index('idx_user_service_account', table_name='user_entity')
    op.drop_table('user_entity')
    op.drop_index('idx_realm_evt_list_realm', table_name='realm_events_listeners')
    op.drop_table('realm_events_listeners')
    op.drop_index('fed_user_attr_long_values', table_name='fed_user_attribute')
    op.drop_index('fed_user_attr_long_values_lower_case', table_name='fed_user_attribute')
    op.drop_index('idx_fu_attribute', table_name='fed_user_attribute')
    op.drop_table('fed_user_attribute')
    op.drop_table('resource_attribute')
    op.drop_index('idx_realm_def_grp_realm', table_name='realm_default_groups')
    op.drop_table('realm_default_groups')
    op.drop_table('required_action_config')
    op.drop_table('realm_required_credential')
    op.drop_index('idx_event_time', table_name='event_entity')
    op.drop_table('event_entity')
    op.drop_index('idx_web_orig_client', table_name='web_origins')
    op.drop_table('web_origins')
    op.drop_table('user_session')
    op.drop_table('policy_config')
    op.drop_table('broker_link')
    op.drop_table('client_session_auth_status')
    op.drop_index('idx_user_role_mapping', table_name='user_role_mapping')
    op.drop_table('user_role_mapping')
    op.drop_index('idx_user_consent', table_name='user_consent')
    op.drop_table('user_consent')
    op.drop_index('idx_fu_role_mapping', table_name='fed_user_role_mapping')
    op.drop_index('idx_fu_role_mapping_ru', table_name='fed_user_role_mapping')
    op.drop_table('fed_user_role_mapping')
    op.drop_index('idx_compo_config_compo', table_name='component_config')
    op.drop_table('component_config')
    op.drop_index('idx_res_srv_res_res_srv', table_name='resource_server_resource')
    op.drop_table('resource_server_resource')
    op.drop_table('client_node_registrations')
    op.drop_index('idx_auth_exec_flow', table_name='authentication_execution')
    op.drop_index('idx_auth_exec_realm_flow', table_name='authentication_execution')
    op.drop_table('authentication_execution')
    op.drop_index('idx_clscope_attrs', table_name='client_scope_attributes')
    op.drop_table('client_scope_attributes')
    op.drop_index('idx_res_policy_policy', table_name='resource_policy')
    op.drop_table('resource_policy')
    op.drop_table('org_domain')
    op.drop_table('client_session_role')
    op.drop_index('idx_user_credential', table_name='credential')
    op.drop_table('credential')
    op.drop_index('idx_perm_ticket_owner', table_name='resource_server_perm_ticket')
    op.drop_index('idx_perm_ticket_requester', table_name='resource_server_perm_ticket')
    op.drop_table('resource_server_perm_ticket')
    op.drop_table('databasechangelog')
    op.drop_index('idx_res_srv_scope_res_srv', table_name='resource_server_scope')
    op.drop_table('resource_server_scope')
    op.drop_index('idx_admin_event_time', table_name='admin_event_entity')
    op.drop_table('admin_event_entity')
    op.drop_table('org')
    op.drop_index('idx_realm_evt_types_realm', table_name='realm_enabled_event_types')
    op.drop_table('realm_enabled_event_types')
    op.drop_index('idx_client_att_by_name_value', table_name='client_attributes')
    op.drop_table('client_attributes')
    op.drop_index('idx_assoc_pol_assoc_pol_id', table_name='associated_policy')
    op.drop_table('associated_policy')
    op.drop_index('idx_redir_uri_client', table_name='redirect_uris')
    op.drop_table('redirect_uris')
    op.drop_table('resource_uris')
    op.drop_index('idx_fu_required_action', table_name='fed_user_required_action')
    op.drop_index('idx_fu_required_action_ru', table_name='fed_user_required_action')
    op.drop_table('fed_user_required_action')
    op.drop_table('protocol_mapper_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocol_mapper_config',
    sa.Column('protocol_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['protocol_mapper_id'], ['protocol_mapper.id'], name='fk_pmconfig'),
    sa.PrimaryKeyConstraint('protocol_mapper_id', 'name', name='constraint_pmconfig')
    )
    op.create_table('fed_user_required_action',
    sa.Column('required_action', sa.VARCHAR(length=255), server_default=sa.text("' '::character varying"), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('required_action', 'user_id', name='constr_fed_required_action')
    )
    op.create_index('idx_fu_required_action_ru', 'fed_user_required_action', ['realm_id', 'user_id'], unique=False)
    op.create_index('idx_fu_required_action', 'fed_user_required_action', ['user_id', 'required_action'], unique=False)
    op.create_table('resource_uris',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name='fk_resource_server_uris'),
    sa.PrimaryKeyConstraint('resource_id', 'value', name='constraint_resour_uris_pk')
    )
    op.create_table('redirect_uris',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_1burs8pb4ouj97h5wuppahv9f'),
    sa.PrimaryKeyConstraint('client_id', 'value', name='constraint_redirect_uris')
    )
    op.create_index('idx_redir_uri_client', 'redirect_uris', ['client_id'], unique=False)
    op.create_table('associated_policy',
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('associated_policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['associated_policy_id'], ['resource_server_policy.id'], name='fk_frsr5s213xcx4wnkog82ssrfy'),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name='fk_frsrpas14xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('policy_id', 'associated_policy_id', name='constraint_farsrpap')
    )
    op.create_index('idx_assoc_pol_assoc_pol_id', 'associated_policy', ['associated_policy_id'], unique=False)
    op.create_table('client_attributes',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk3c47c64beacca966'),
    sa.PrimaryKeyConstraint('client_id', 'name', name='constraint_3c')
    )
    op.create_index('idx_client_att_by_name_value', 'client_attributes', ['name', sa.text('substr(value, 1, 255)')], unique=False)
    op.create_table('realm_enabled_event_types',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_h846o4h0w8epx5nwedrf5y69j'),
    sa.PrimaryKeyConstraint('realm_id', 'value', name='constr_realm_enabl_event_types')
    )
    op.create_index('idx_realm_evt_types_realm', 'realm_enabled_event_types', ['realm_id'], unique=False)
    op.create_table('org',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ORG_pkey'),
    sa.UniqueConstraint('group_id', name='uk_org_group'),
    sa.UniqueConstraint('realm_id', 'name', name='uk_org_name')
    )
    op.create_table('admin_event_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('admin_event_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_path', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('representation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constraint_admin_event_entity')
    )
    op.create_index('idx_admin_event_time', 'admin_event_entity', ['realm_id', 'admin_event_time'], unique=False)
    op.create_table('resource_server_scope',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('icon_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name='fk_frsrso213xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('id', name='constraint_farsrs'),
    sa.UniqueConstraint('name', 'resource_server_id', name='uk_frsrst700s9v50bu18ws5ha6'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_res_srv_scope_res_srv', 'resource_server_scope', ['resource_server_id'], unique=False)
    op.create_table('databasechangelog',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('dateexecuted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('orderexecuted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exectype', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('md5sum', sa.VARCHAR(length=35), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tag', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('liquibase', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('contexts', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('labels', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('deployment_id', sa.VARCHAR(length=10), autoincrement=False, nullable=True)
    )
    op.create_table('resource_server_perm_ticket',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('requester', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('granted_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name='fk_frsrpo2128cx4wnkog82ssrfy'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name='fk_frsrho213xcx4wnkog83sspmt'),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name='fk_frsrho213xcx4wnkog82sspmt'),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name='fk_frsrho213xcx4wnkog84sspmt'),
    sa.PrimaryKeyConstraint('id', name='constraint_fapmt'),
    sa.UniqueConstraint('owner', 'requester', 'resource_server_id', 'resource_id', 'scope_id', name='uk_frsr6t700s9v50bu18ws5pmt')
    )
    op.create_index('idx_perm_ticket_requester', 'resource_server_perm_ticket', ['requester'], unique=False)
    op.create_index('idx_perm_ticket_owner', 'resource_server_perm_ticket', ['owner'], unique=False)
    op.create_table('credential',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secret_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credential_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_pfyr0glasqyl0dei3kl69r6v0'),
    sa.PrimaryKeyConstraint('id', name='constraint_f')
    )
    op.create_index('idx_user_credential', 'credential', ['user_id'], unique=False)
    op.create_table('client_session_role',
    sa.Column('role_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name='fk_11b7sgqw18i532811v7o2dv76'),
    sa.PrimaryKeyConstraint('client_session', 'role_id', name='constraint_5')
    )
    op.create_table('org_domain',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('org_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', 'name', name='ORG_DOMAIN_pkey')
    )
    op.create_table('resource_policy',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name='fk_frsrpp213xcx4wnkog82ssrfy'),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name='fk_frsrpos53xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('resource_id', 'policy_id', name='constraint_farsrpp')
    )
    op.create_index('idx_res_policy_policy', 'resource_policy', ['policy_id'], unique=False)
    op.create_table('client_scope_attributes',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['client_scope.id'], name='fk_cl_scope_attr_scope'),
    sa.PrimaryKeyConstraint('scope_id', 'name', name='pk_cl_tmpl_attr')
    )
    op.create_index('idx_clscope_attrs', 'client_scope_attributes', ['scope_id'], unique=False)
    op.create_table('authentication_execution',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('authenticator', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('requirement', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('authenticator_flow', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auth_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('auth_config', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['authentication_flow.id'], name='fk_auth_exec_flow'),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_auth_exec_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_auth_exec_pk')
    )
    op.create_index('idx_auth_exec_realm_flow', 'authentication_execution', ['realm_id', 'flow_id'], unique=False)
    op.create_index('idx_auth_exec_flow', 'authentication_execution', ['flow_id'], unique=False)
    op.create_table('client_node_registrations',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk4129723ba992f594'),
    sa.PrimaryKeyConstraint('client_id', 'name', name='constraint_84')
    )
    op.create_table('resource_server_resource',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('icon_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner_managed_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name='fk_frsrho213xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('id', name='constraint_farsr'),
    sa.UniqueConstraint('name', 'owner', 'resource_server_id', name='uk_frsr6t700s9v50bu18ws5ha6'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_res_srv_res_res_srv', 'resource_server_resource', ['resource_server_id'], unique=False)
    op.create_table('component_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('component_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['component.id'], name='fk_component_config'),
    sa.PrimaryKeyConstraint('id', name='constr_component_config_pk')
    )
    op.create_index('idx_compo_config_compo', 'component_config', ['component_id'], unique=False)
    op.create_table('fed_user_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id', 'user_id', name='constr_fed_user_role')
    )
    op.create_index('idx_fu_role_mapping_ru', 'fed_user_role_mapping', ['realm_id', 'user_id'], unique=False)
    op.create_index('idx_fu_role_mapping', 'fed_user_role_mapping', ['user_id', 'role_id'], unique=False)
    op.create_table('user_consent',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('external_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_grntcsnt_user'),
    sa.PrimaryKeyConstraint('id', name='constraint_grntcsnt_pm'),
    sa.UniqueConstraint('client_id', 'user_id', name='uk_local_consent'),
    sa.UniqueConstraint('client_storage_provider', 'external_client_id', 'user_id', name='uk_external_consent'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_user_consent', 'user_consent', ['user_id'], unique=False)
    op.create_table('user_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_c4fqv34p1mbylloxang7b1q3l'),
    sa.PrimaryKeyConstraint('role_id', 'user_id', name='constraint_c')
    )
    op.create_index('idx_user_role_mapping', 'user_role_mapping', ['user_id'], unique=False)
    op.create_table('client_session_auth_status',
    sa.Column('authenticator', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name='auth_status_constraint'),
    sa.PrimaryKeyConstraint('client_session', 'authenticator', name='constraint_auth_status_pk')
    )
    op.create_table('broker_link',
    sa.Column('identity_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('broker_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('broker_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('identity_provider', 'user_id', name='constr_broker_link_pk')
    )
    op.create_table('policy_config',
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name='fkdc34197cf864c4e43'),
    sa.PrimaryKeyConstraint('policy_id', 'name', name='constraint_dpc')
    )
    op.create_table('user_session',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('auth_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_session_refresh', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('login_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('remember_me', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('started', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_session_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('broker_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('broker_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constraint_57'),
    postgresql_ignore_search_path=False
    )
    op.create_table('web_origins',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_lojpho213xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('client_id', 'value', name='constraint_web_origins')
    )
    op.create_index('idx_web_orig_client', 'web_origins', ['client_id'], unique=False)
    op.create_table('event_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details_json', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('event_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('details_json_long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constraint_4')
    )
    op.create_index('idx_event_time', 'event_entity', ['realm_id', 'event_time'], unique=False)
    op.create_table('realm_required_credential',
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('form_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('input', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('secret', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_5hg65lybevavkqfki3kponh9v'),
    sa.PrimaryKeyConstraint('realm_id', 'type', name='constraint_92')
    )
    op.create_table('required_action_config',
    sa.Column('required_action_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('required_action_id', 'name', name='constraint_req_act_cfg_pk')
    )
    op.create_table('realm_default_groups',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_def_groups_realm'),
    sa.PrimaryKeyConstraint('realm_id', 'group_id', name='constr_realm_default_groups'),
    sa.UniqueConstraint('group_id', name='con_group_id_def_groups')
    )
    op.create_index('idx_realm_def_grp_realm', 'realm_default_groups', ['realm_id'], unique=False)
    op.create_table('resource_attribute',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name='fk_5hrm2vlf9ql5fu022kqepovbr'),
    sa.PrimaryKeyConstraint('id', name='res_attr_pk')
    )
    op.create_table('fed_user_attribute',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('value', sa.VARCHAR(length=2024), autoincrement=False, nullable=True),
    sa.Column('long_value_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value_hash_lower_case', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constr_fed_user_attr_pk')
    )
    op.create_index('idx_fu_attribute', 'fed_user_attribute', ['user_id', 'realm_id', 'name'], unique=False)
    op.create_index('fed_user_attr_long_values_lower_case', 'fed_user_attribute', ['long_value_hash_lower_case', 'name'], unique=False)
    op.create_index('fed_user_attr_long_values', 'fed_user_attribute', ['long_value_hash', 'name'], unique=False)
    op.create_table('realm_events_listeners',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_h846o4h0w8epx5nxev9f5y69j'),
    sa.PrimaryKeyConstraint('realm_id', 'value', name='constr_realm_events_listeners')
    )
    op.create_index('idx_realm_evt_list_realm', 'realm_events_listeners', ['realm_id'], unique=False)
    op.create_table('user_entity',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_constraint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('federation_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_timestamp', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('service_account_client_link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='constraint_fb'),
    sa.UniqueConstraint('realm_id', 'email_constraint', name='uk_dykn684sl8up1crfei6eckhd7'),
    sa.UniqueConstraint('realm_id', 'username', name='uk_ru8tt6t700s9v50bu18ws5ha6'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_user_service_account', 'user_entity', ['realm_id', 'service_account_client_link'], unique=False)
    op.create_index('idx_user_email', 'user_entity', ['email'], unique=False)
    op.create_table('group_attribute',
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keycloak_group.id'], name='fk_group_attribute_group'),
    sa.PrimaryKeyConstraint('id', name='constraint_group_attribute_pk')
    )
    op.create_index('idx_group_attr_group', 'group_attribute', ['group_id'], unique=False)
    op.create_index('idx_group_att_by_name_value', 'group_attribute', ['name', sa.text('(value::character varying(250))')], unique=False)
    op.create_table('fed_user_consent_cl_scope',
    sa.Column('user_consent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('user_consent_id', 'scope_id', name='constraint_fgrntcsnt_clsc_pm')
    )
    op.create_table('required_action_provider',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('default_action', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_req_act_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_req_act_prv_pk')
    )
    op.create_index('idx_req_act_prov_realm', 'required_action_provider', ['realm_id'], unique=False)
    op.create_table('scope_policy',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('policy_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['resource_server_policy.id'], name='fk_frsrasp13xcx4wnkog82ssrfy'),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name='fk_frsrpass3xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('scope_id', 'policy_id', name='constraint_farsrsps')
    )
    op.create_index('idx_scope_policy_policy', 'scope_policy', ['policy_id'], unique=False)
    op.create_table('client_initial_access',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remaining_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_client_init_acc_realm'),
    sa.PrimaryKeyConstraint('id', name='cnstr_client_init_acc_pk')
    )
    op.create_index('idx_client_init_acc_realm', 'client_initial_access', ['realm_id'], unique=False)
    op.create_table('identity_provider',
    sa.Column('internal_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('provider_alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('store_token', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('authenticate_by_default', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('add_token_role', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('trust_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('first_broker_login_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('post_broker_login_flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('link_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk2b4ebc52ae5c3b34'),
    sa.PrimaryKeyConstraint('internal_id', name='constraint_2b'),
    sa.UniqueConstraint('provider_alias', 'realm_id', name='uk_2daelwnibji49avxsrtuf6xj33'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_ident_prov_realm', 'identity_provider', ['realm_id'], unique=False)
    op.create_table('user_consent_client_scope',
    sa.Column('user_consent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_consent_id'], ['user_consent.id'], name='fk_grntcsnt_clsc_usc'),
    sa.PrimaryKeyConstraint('user_consent_id', 'scope_id', name='constraint_grntcsnt_clsc_pm')
    )
    op.create_index('idx_usconsent_clscope', 'user_consent_client_scope', ['user_consent_id'], unique=False)
    op.create_table('keycloak_group',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent_group', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constraint_group'),
    sa.UniqueConstraint('realm_id', 'parent_group', 'name', name='sibling_names'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_required_action',
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('required_action', sa.VARCHAR(length=255), server_default=sa.text("' '::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_6qj3w1jw9cvafhe19bwsiuvmd'),
    sa.PrimaryKeyConstraint('required_action', 'user_id', name='constraint_required_action')
    )
    op.create_index('idx_user_reqactions', 'user_required_action', ['user_id'], unique=False)
    op.create_table('realm',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('access_code_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_action_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('access_token_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('admin_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('events_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('events_expiration', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('login_theme', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('password_policy', sa.VARCHAR(length=2550), autoincrement=False, nullable=True),
    sa.Column('registration_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('remember_me', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('reset_password_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('social', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('ssl_required', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sso_idle_timeout', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sso_max_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('update_profile_on_soc_login', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verify_email', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('master_admin_client', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('login_lifespan', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('internationalization_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('default_locale', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('reg_email_as_username', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin_events_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('admin_events_details_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('edit_username_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('otp_policy_counter', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_window', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_period', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_digits', sa.INTEGER(), server_default=sa.text('6'), autoincrement=False, nullable=True),
    sa.Column('otp_policy_alg', sa.VARCHAR(length=36), server_default=sa.text("'HmacSHA1'::character varying"), autoincrement=False, nullable=True),
    sa.Column('otp_policy_type', sa.VARCHAR(length=36), server_default=sa.text("'totp'::character varying"), autoincrement=False, nullable=True),
    sa.Column('browser_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('registration_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('direct_grant_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('reset_credentials_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('client_auth_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('offline_session_idle_timeout', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('revoke_refresh_token', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('access_token_life_implicit', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('login_with_email_allowed', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('duplicate_emails_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('docker_auth_flow', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('refresh_token_max_reuse', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('allow_user_managed_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sso_max_lifespan_remember_me', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sso_idle_timeout_remember_me', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('default_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constraint_4a'),
    sa.UniqueConstraint('name', name='uk_orvsdmla56612eaefiq6wl5oi'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_realm_master_adm_cli', 'realm', ['master_admin_client'], unique=False)
    op.create_table('user_federation_config',
    sa.Column('user_federation_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_federation_provider_id'], ['user_federation_provider.id'], name='fk_t13hpu1j94r2ebpekr39x5eu5'),
    sa.PrimaryKeyConstraint('user_federation_provider_id', 'name', name='constraint_f9')
    )
    op.create_table('realm_supported_locales',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_supported_locales_realm'),
    sa.PrimaryKeyConstraint('realm_id', 'value', name='constr_realm_supported_locales')
    )
    op.create_index('idx_realm_supp_local_realm', 'realm_supported_locales', ['realm_id'], unique=False)
    op.create_table('username_login_failure',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('failed_login_not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_failure', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_ip_failure', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('num_failures', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('realm_id', 'username', name='CONSTRAINT_17-2')
    )
    op.create_table('client_session',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('redirect_uri', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('auth_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('auth_user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('current_action', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['user_session.id'], name='fk_b4ao2vcvat6ukau74wbwtfqo1'),
    sa.PrimaryKeyConstraint('id', name='constraint_8'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_client_session_session', 'client_session', ['session_id'], unique=False)
    op.create_table('user_federation_mapper_config',
    sa.Column('user_federation_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_federation_mapper_id'], ['user_federation_mapper.id'], name='fk_fedmapper_cfg'),
    sa.PrimaryKeyConstraint('user_federation_mapper_id', 'name', name='constraint_fedmapper_cfg_pm')
    )
    op.create_table('client_scope_role_mapping',
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['client_scope.id'], name='fk_cl_scope_rm_scope'),
    sa.PrimaryKeyConstraint('scope_id', 'role_id', name='pk_template_scope')
    )
    op.create_index('idx_role_clscope', 'client_scope_role_mapping', ['role_id'], unique=False)
    op.create_index('idx_clscope_role', 'client_scope_role_mapping', ['scope_id'], unique=False)
    op.create_table('group_role_mapping',
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['keycloak_group.id'], name='fk_group_role_group'),
    sa.PrimaryKeyConstraint('role_id', 'group_id', name='constraint_group_role')
    )
    op.create_index('idx_group_role_mapp_group', 'group_role_mapping', ['group_id'], unique=False)
    op.create_table('migration_model',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('update_time', sa.BIGINT(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='constraint_migmod')
    )
    op.create_index('idx_update_time', 'migration_model', ['update_time'], unique=False)
    op.create_table('user_attribute',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(length=36), server_default=sa.text("'sybase-needs-something-here'::character varying"), autoincrement=False, nullable=False),
    sa.Column('long_value_hash', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value_hash_lower_case', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('long_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_5hrm2vlf9ql5fu043kqepovbr'),
    sa.PrimaryKeyConstraint('id', name='constraint_user_attribute_pk')
    )
    op.create_index('user_attr_long_values_lower_case', 'user_attribute', ['long_value_hash_lower_case', 'name'], unique=False)
    op.create_index('user_attr_long_values', 'user_attribute', ['long_value_hash', 'name'], unique=False)
    op.create_index('idx_user_attribute_name', 'user_attribute', ['name', 'value'], unique=False)
    op.create_index('idx_user_attribute', 'user_attribute', ['user_id'], unique=False)
    op.create_table('scope_mapping',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_ouse064plmlr732lxjcn1q5f1'),
    sa.PrimaryKeyConstraint('client_id', 'role_id', name='constraint_81')
    )
    op.create_index('idx_scope_mapping_role', 'scope_mapping', ['role_id'], unique=False)
    op.create_table('client_session_note',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name='fk5edfb00ff51c2736'),
    sa.PrimaryKeyConstraint('client_session', 'name', name='constraint_5e')
    )
    op.create_table('user_group_membership',
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk_user_group_user'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name='constraint_user_group')
    )
    op.create_index('idx_user_group_mapping', 'user_group_membership', ['user_id'], unique=False)
    op.create_table('user_session_note',
    sa.Column('user_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_session'], ['user_session.id'], name='fk5edfb00ff51d3472'),
    sa.PrimaryKeyConstraint('user_session', 'name', name='constraint_usn_pk')
    )
    op.create_table('federated_identity',
    sa.Column('identity_provider', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('federated_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('federated_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_entity.id'], name='fk404288b92ef007a6'),
    sa.PrimaryKeyConstraint('identity_provider', 'user_id', name='constraint_40')
    )
    op.create_index('idx_fedidentity_user', 'federated_identity', ['user_id'], unique=False)
    op.create_index('idx_fedidentity_feduser', 'federated_identity', ['federated_user_id'], unique=False)
    op.create_table('client_scope',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_cli_template'),
    sa.UniqueConstraint('realm_id', 'name', name='uk_cli_scope'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_realm_clscope', 'client_scope', ['realm_id'], unique=False)
    op.create_table('offline_user_session',
    sa.Column('user_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created_on', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('offline_flag', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_session_refresh', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('broker_session_id', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_session_id', 'offline_flag', name='constraint_offl_us_ses_pk2')
    )
    op.create_index('idx_offline_uss_by_user', 'offline_user_session', ['user_id', 'realm_id', 'offline_flag'], unique=False)
    op.create_index('idx_offline_uss_by_last_session_refresh', 'offline_user_session', ['realm_id', 'offline_flag', 'last_session_refresh'], unique=False)
    op.create_index('idx_offline_uss_by_broker_session_id', 'offline_user_session', ['broker_session_id', 'realm_id'], unique=False)
    op.create_table('client_user_session_note',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name='fk_cl_usr_ses_note'),
    sa.PrimaryKeyConstraint('client_session', 'name', name='constr_cl_usr_ses_note')
    )
    op.create_table('resource_server_policy',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('decision_strategy', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('logic', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('resource_server_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['resource_server_id'], ['resource_server.id'], name='fk_frsrpo213xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('id', name='constraint_farsrp'),
    sa.UniqueConstraint('name', 'resource_server_id', name='uk_frsrpt700s9v50bu18ws5ha6')
    )
    op.create_index('idx_res_serv_pol_res_serv', 'resource_server_policy', ['resource_server_id'], unique=False)
    op.create_table('resource_scope',
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_server_resource.id'], name='fk_frsrpos13xcx4wnkog82ssrfy'),
    sa.ForeignKeyConstraint(['scope_id'], ['resource_server_scope.id'], name='fk_frsrps213xcx4wnkog82ssrfy'),
    sa.PrimaryKeyConstraint('resource_id', 'scope_id', name='constraint_farsrsp')
    )
    op.create_index('idx_res_scope_scope', 'resource_scope', ['scope_id'], unique=False)
    op.create_table('federated_user',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='constr_federated_user')
    )
    op.create_table('client_auth_flow_bindings',
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('flow_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('binding_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'binding_name', name='c_cli_flow_bind')
    )
    op.create_table('client_session_prot_mapper',
    sa.Column('protocol_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_session', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_session'], ['client_session.id'], name='fk_33a8sgqw18i532811v7o2dk89'),
    sa.PrimaryKeyConstraint('client_session', 'protocol_mapper_id', name='constraint_cs_pmp_pk')
    )
    op.create_table('offline_client_session',
    sa.Column('user_session_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('offline_flag', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('external_client_id', sa.VARCHAR(length=255), server_default=sa.text("'local'::character varying"), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_session_id', 'client_id', 'client_storage_provider', 'external_client_id', 'offline_flag', name='constraint_offl_cl_ses_pk3')
    )
    op.create_index('idx_us_sess_id_on_cl_sess', 'offline_client_session', ['user_session_id'], unique=False)
    op.create_table('user_federation_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('federation_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('federation_mapper_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['federation_provider_id'], ['user_federation_provider.id'], name='fk_fedmapperpm_fedprv'),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_fedmapperpm_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_fedmapperpm')
    )
    op.create_index('idx_usr_fed_map_realm', 'user_federation_mapper', ['realm_id'], unique=False)
    op.create_index('idx_usr_fed_map_fed_prv', 'user_federation_mapper', ['federation_provider_id'], unique=False)
    op.create_table('client_scope_client',
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('default_scope', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('client_id', 'scope_id', name='c_cli_scope_bind')
    )
    op.create_index('idx_clscope_cl', 'client_scope_client', ['client_id'], unique=False)
    op.create_index('idx_cl_clscope', 'client_scope_client', ['scope_id'], unique=False)
    op.create_table('realm_attribute',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_8shxd6l3e9atqukacxgpffptw'),
    sa.PrimaryKeyConstraint('name', 'realm_id', name='constraint_9')
    )
    op.create_index('idx_realm_attr_realm', 'realm_attribute', ['realm_id'], unique=False)
    op.create_table('identity_provider_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('idp_alias', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('idp_mapper_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_idpm_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_idpm'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_id_prov_mapp_realm', 'identity_provider_mapper', ['realm_id'], unique=False)
    op.create_table('keycloak_role',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_realm_constraint', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client_role', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('client', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('realm', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm'], ['realm.id'], name='fk_6vyqfe4cn4wlq8r6kt5vdsj5c'),
    sa.PrimaryKeyConstraint('id', name='constraint_a'),
    sa.UniqueConstraint('name', 'client_realm_constraint', name='UK_J3RWUVD56ONTGSUHOGM184WW2-2'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_keycloak_role_realm', 'keycloak_role', ['realm'], unique=False)
    op.create_index('idx_keycloak_role_client', 'keycloak_role', ['client'], unique=False)
    op.create_table('idp_mapper_config',
    sa.Column('idp_mapper_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idp_mapper_id'], ['identity_provider_mapper.id'], name='fk_idpmconfig'),
    sa.PrimaryKeyConstraint('idp_mapper_id', 'name', name='constraint_idpmconfig')
    )
    op.create_table('composite_role',
    sa.Column('composite', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('child_role', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['child_role'], ['keycloak_role.id'], name='fk_gr7thllb9lu8q4vqa4524jjy8'),
    sa.ForeignKeyConstraint(['composite'], ['keycloak_role.id'], name='fk_a63wvekftu8jo1pnj81e7mce2'),
    sa.PrimaryKeyConstraint('composite', 'child_role', name='constraint_composite_role')
    )
    op.create_index('idx_composite_child', 'composite_role', ['child_role'], unique=False)
    op.create_index('idx_composite', 'composite_role', ['composite'], unique=False)
    op.create_table('component',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('parent_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('sub_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_component_realm'),
    sa.PrimaryKeyConstraint('id', name='constr_component_pk')
    )
    op.create_index('idx_component_realm', 'component', ['realm_id'], unique=False)
    op.create_index('idx_component_provider_type', 'component', ['provider_type'], unique=False)
    op.create_table('authenticator_config_entry',
    sa.Column('authenticator_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('authenticator_id', 'name', name='constraint_auth_cfg_pk')
    )
    op.create_table('client',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('full_scope_allowed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('not_before', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('public_client', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('bearer_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('management_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('surrogate_auth_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('node_rereg_timeout', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('frontchannel_logout', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('consent_required', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('service_accounts_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('client_authenticator_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('root_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('registration_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('standard_flow_enabled', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('implicit_flow_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('direct_access_grants_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('always_display_in_console', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='constraint_7'),
    sa.UniqueConstraint('realm_id', 'client_id', name='uk_b71cjlbenv945rb6gcon438at'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_client_id', 'client', ['client_id'], unique=False)
    op.create_table('realm_localizations',
    sa.Column('realm_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('locale', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('texts', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('realm_id', 'locale', name='realm_localizations_pkey')
    )
    op.create_table('fed_user_group_membership',
    sa.Column('group_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name='constr_fed_user_group')
    )
    op.create_index('idx_fu_group_membership_ru', 'fed_user_group_membership', ['realm_id', 'user_id'], unique=False)
    op.create_index('idx_fu_group_membership', 'fed_user_group_membership', ['user_id', 'group_id'], unique=False)
    op.create_table('fed_user_consent',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('last_updated_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('client_storage_provider', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('external_client_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constr_fed_user_consent_pk')
    )
    op.create_index('idx_fu_consent_ru', 'fed_user_consent', ['realm_id', 'user_id'], unique=False)
    op.create_index('idx_fu_consent', 'fed_user_consent', ['user_id', 'client_id'], unique=False)
    op.create_index('idx_fu_cnsnt_ext', 'fed_user_consent', ['user_id', 'client_storage_provider', 'external_client_id'], unique=False)
    op.create_table('user_federation_provider',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('changed_sync_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('full_sync_period', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_sync', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_1fj32f6ptolw2qy60cd8n01e8'),
    sa.PrimaryKeyConstraint('id', name='constraint_5c')
    )
    op.create_index('idx_usr_fed_prv_realm', 'user_federation_provider', ['realm_id'], unique=False)
    op.create_table('authenticator_config',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_auth_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_auth_pk')
    )
    op.create_index('idx_auth_config_realm', 'authenticator_config', ['realm_id'], unique=False)
    op.create_table('realm_smtp_config',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_70ej8xdxgxd0b9hh6180irr0o'),
    sa.PrimaryKeyConstraint('realm_id', 'name', name='constraint_e')
    )
    op.create_table('protocol_mapper',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('protocol', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('protocol_mapper_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('client_scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='fk_pcm_realm'),
    sa.ForeignKeyConstraint(['client_scope_id'], ['client_scope.id'], name='fk_cli_scope_mapper'),
    sa.PrimaryKeyConstraint('id', name='constraint_pcm')
    )
    op.create_index('idx_protocol_mapper_client', 'protocol_mapper', ['client_id'], unique=False)
    op.create_index('idx_clscope_protmap', 'protocol_mapper', ['client_scope_id'], unique=False)
    op.create_table('role_attribute',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['keycloak_role.id'], name='fk_role_attribute_id'),
    sa.PrimaryKeyConstraint('id', name='constraint_role_attribute_pk')
    )
    op.create_index('idx_role_attribute', 'role_attribute', ['role_id'], unique=False)
    op.create_table('databasechangeloglock',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('lockgranted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('lockedby', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='databasechangeloglock_pkey')
    )
    op.create_table('resource_server',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('allow_rs_remote_mgmt', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('policy_enforce_mode', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('decision_strategy', sa.SMALLINT(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_resource_server')
    )
    op.create_table('fed_user_credential',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('salt', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_date', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('storage_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('user_label', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('secret_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('credential_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='constr_fed_user_cred_pk')
    )
    op.create_index('idx_fu_credential_ru', 'fed_user_credential', ['realm_id', 'user_id'], unique=False)
    op.create_index('idx_fu_credential', 'fed_user_credential', ['user_id', 'type'], unique=False)
    op.create_table('default_client_scope',
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('scope_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('default_scope', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_r_def_cli_scope_realm'),
    sa.PrimaryKeyConstraint('realm_id', 'scope_id', name='r_def_cli_scope_bind')
    )
    op.create_index('idx_defcls_scope', 'default_client_scope', ['scope_id'], unique=False)
    op.create_index('idx_defcls_realm', 'default_client_scope', ['realm_id'], unique=False)
    op.create_table('authentication_flow',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('alias', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('realm_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('provider_id', sa.VARCHAR(length=36), server_default=sa.text("'basic-flow'::character varying"), autoincrement=False, nullable=False),
    sa.Column('top_level', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('built_in', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['realm_id'], ['realm.id'], name='fk_auth_flow_realm'),
    sa.PrimaryKeyConstraint('id', name='constraint_auth_flow_pk')
    )
    op.create_index('idx_auth_flow_realm', 'authentication_flow', ['realm_id'], unique=False)
    op.create_table('identity_provider_config',
    sa.Column('identity_provider_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['identity_provider_id'], ['identity_provider.internal_id'], name='fkdc4897cf864c4e43'),
    sa.PrimaryKeyConstraint('identity_provider_id', 'name', name='constraint_d')
    )
    # ### end Alembic commands ###
